### ISSUE TITLE
Where do I configure the apikey and apisecret

### ISSUE THREAD

**Issue by rocheston** [nexmo-community/video-with-text-chat#1]
Where to add these? Which file. Please give instructions to add apikey and apisecret

**Comment by rocheston** [comment]
sudo node server.js
/home/-------/node_modules/opentok/lib/opentok.js:79
    throw new Error('Invalid arguments when initializing OpenTok: apiKey=' + apiKey + ', apiSecret=' + apiSecret);
    ^

Error: Invalid arguments when initializing OpenTok: apiKey=undefined, apiSecret=undefined
    at new OpenTok (/home/------/node_modules/opentok/lib/opentok.js:79:11)
    at Object.<anonymous> (/home/---------/server.js:8:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by lornajane** [comment]
Copy the `.env.example` to `.env` and then add your details there if you're running locally. If you're using Glitch, you can set the environment variables through the web interface. Hope that helps .... let us know?

**Comment by lornajane** [comment]
I'm going to close this for now but please get in touch if you need anything more from us!
